version: "3.5"
services:
  nginx:
    container_name: test_nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infra-net
  app1:
    container_name: test_app_1
    build: ./app1
    networks:
      - infra-net
  app2:
    container_name: test_app_2
    build: ./app2
    networks:
      - infra-net
networks:
  infra-net:
    driver: bridge
